## Import libraries

In [22]:
import pandas as pd
import numpy as np

# Show all columns
pd.set_option('display.max_columns', None)

## Load the dataset

In [23]:
merged_df = pd.read_csv(r'./data/merged.csv', low_memory=False)

Let's take a quick look at the dataset:

In [24]:
merged_df

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval,Year,Month,Day,CompetitionOpen
0,1,5,2015-07-31,5263,555,1,1,0,1,c,a,1270.0,9.0,2008.0,0,0.0,0.0,0,2015,7,31,82.0
1,2,5,2015-07-31,6064,625,1,1,0,1,a,a,570.0,11.0,2007.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct",2015,7,31,92.0
2,3,5,2015-07-31,8314,821,1,1,0,1,a,a,14130.0,12.0,2006.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct",2015,7,31,103.0
3,4,5,2015-07-31,13995,1498,1,1,0,1,c,c,620.0,9.0,2009.0,0,0.0,0.0,0,2015,7,31,70.0
4,5,5,2015-07-31,4822,559,1,1,0,1,a,a,29910.0,4.0,2015.0,0,0.0,0.0,0,2015,7,31,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
844333,682,2,2013-01-01,3375,566,1,0,a,1,b,a,150.0,9.0,2006.0,0,0.0,0.0,0,2013,1,1,76.0
844334,733,2,2013-01-01,10765,2377,1,0,a,1,b,b,860.0,10.0,1999.0,0,0.0,0.0,0,2013,1,1,159.0
844335,769,2,2013-01-01,5035,1248,1,0,a,1,b,b,840.0,NaN,NaN,1,48.0,2012.0,"Jan,Apr,Jul,Oct",2013,1,1,0.0
844336,948,2,2013-01-01,4491,1039,1,0,a,1,b,b,1430.0,NaN,NaN,0,0.0,0.0,0,2013,1,1,0.0
844337,1097,2,2013-01-01,5961,1405,1,0,a,1,b,b,720.0,3.0,2002.0,0,0.0,0.0,0,2013,1,1,130.0

## Train-Test split

In [25]:
# change the Dtype of Date column
merged_df['Date'] = pd.to_datetime(merged_df['Date'])

In [26]:
# set the cutoff
cutoff = merged_df['Date'].max() - pd.Timedelta(weeks=6)

In [27]:
train = merged_df[merged_df['Date'] <= cutoff]
test = merged_df[merged_df['Date'] > cutoff]

In [28]:
X_train = train.drop('Sales', axis=1)
X_test = test.drop('Sales', axis=1)
y_train = train['Sales']
y_test = test['Sales']

Let's decide Input and Traget columns:

In [29]:
input_cols = ['DayOfWeek', 'Customers', 'Open',
              'Promo', 'StateHoliday', 'SchoolHoliday',
              'StoreType', 'Assortment', 'CompetitionDistance',
              'CompetitionOpen','Promo2', 'Promo2SinceWeek',
              'Promo2SinceYear', 'Year', 'Month', 'Day']

target_cols = 'Sales'

Let's separate `categorical` and `numerical` columns from input columns for `Encoding` and `Scaling` respectively,
note that we can treat binary categorical columns(0/1) as numeric columns *(Because with only two values, the “distance between values” problem disappears)*:

In [30]:
cat_cols = ['DayOfWeek', 'StoreType', 'Assortment', 'StateHoliday']

num_cols = ['Customers', 'Open', 'Promo', 'SchoolHoliday',
            'CompetitionDistance', 'CompetitionOpen', 'Promo2', 'Promo2SinceWeek',
            'Promo2SinceYear', 'Year', 'Month', 'Day']

## Preprocessing

#### Encoding categorical columns

In [31]:
from sklearn.preprocessing import OneHotEncoder

In [32]:
encoder = OneHotEncoder(sparse_output=False)

In [33]:
X_train_encoded = encoder.fit_transform(X_train[cat_cols])
X_test_encoded = encoder.transform(X_test[cat_cols])

#### Scaling numerical columns

In [34]:
from sklearn.preprocessing import StandardScaler

In [35]:
scaler = StandardScaler()

In [36]:
X_train_scaled = scaler.fit_transform(X_train[num_cols])
X_test_scaled = scaler.transform(X_test[num_cols])

#### Combine Encoded and Scaled columns

In [37]:
X_train_final = np.hstack([X_train_encoded, X_train_scaled])
X_test_final = np.hstack([X_test_encoded, X_test_scaled])

Let's check their shape before we go further:

In [38]:
X_train_final.shape, X_test_final.shape

((804056, 30), (40282, 30))

## Baseline Random Forest

In [39]:
from sklearn.ensemble import RandomForestRegressor

In [40]:
rf = RandomForestRegressor(random_state=42, n_jobs=-1)

Let's train this baseline model:

In [41]:
rf.fit(X_train_final, y_train)

RandomForestRegressor(n_jobs=-1, random_state=42)

Let's predict using this trained baseline model:

In [42]:
rf_preds = rf.predict(X_test_final)

Let's evaluate our baseline model using `MAE`, and `R-Squared` from `sklearn`:

In [43]:
from sklearn.metrics import mean_absolute_error, root_mean_squared_error, r2_score

In [44]:
rf_mae = mean_absolute_error(y_test, rf_preds)
print('Baseline Random Forest MAE:', rf_mae)

Baseline Random Forest MAE: 392.44207555483837

Our baseline **Random forest** model is off by about **€392** (in either direction).

In [45]:
y_test_mean = y_test.mean()
print('y_test_mean:', y_test_mean)

y_test_mean: 6978.638051735266

Our basline **Random Forest**'s MAE is about `5.6%` of the **average daily sales**.\
To put it simply: if average daily sales were 100, the model would typically predict somewhere around 95 to 105.

In [46]:
rf_r2 = r2_score(y_test, rf_preds)
print('Baseline Random Forest R-Sqauared:', rf_r2)

Baseline Random Forest R-Sqauared: 0.9615149375036403

Our baseline model is able to explain 96% of the variance in daily sales.

**Next:** Let's check feature importnace our baseline **Random Forest** but first let's get all the features:

In [ ]:
# Features from encoding
encoded_features = encoder.get_feature_names_out()

In [ ]:
# Features from scaling
scaled_features = scaler.get_feature_names_out()

In [ ]:
# concatenate features from encoding and scaling
all_features = np.concatenate([encoded_features, scaled_features])

In [82]:
pd.DataFrame({
    'Feature': all_features,
    'Importance': rf.feature_importances_
}).sort_values('Importance', ascending=False).head(10)

                Feature  Importance
18            Customers    0.742715
22  CompetitionDistance    0.069057
10          StoreType_d    0.043926
20                Promo    0.032906
12         Assortment_b    0.019645
23      CompetitionOpen    0.018412
25      Promo2SinceWeek    0.014962
8           StoreType_b    0.009965
26      Promo2SinceYear    0.008581
28                Month    0.007021

So according to our basline random forest, the most important feature is **`Customers`**, meaning a store with\
most customers will have the most sales on everyday basis.

## Baseline XGBoost

In [47]:
from xgboost import XGBRegressor

In [48]:
xgb = XGBRegressor(random_state=42, n_jobs=-1)

Let's train our baseline XGBoost model:

In [49]:
xgb.fit(X_train_final, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=True, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=None,
             n_jobs=-1, num_parallel_tree=None, ...)

Let's predict using this trained baseline model:

In [50]:
xgb_preds = xgb.predict(X_test_final)

Now, Let's evaluate our basline model using the same matrics as before:

In [51]:
xgb_mae = mean_absolute_error(y_test, xgb_preds)
print("Baseline XGBoost MAE:", xgb_mae)

Baseline XGBoost MAE: 501.51959228515625

Our baseline **XGBoost** model is off by about **€501.5**, which is worse than our baseline **Random forest** model (€392).

In [52]:
y_test_mean = y_test.mean()
print('y_test_mean:', y_test_mean)

y_test_mean: 6978.638051735266

Our basline **XGBoost**'s MAE is about `7%` of the **average daily sales**.

In [53]:
xgb_r2 = r2_score(y_test, xgb_preds)
print("Baseline XGBoost R-Squared:", xgb_r2)

Baseline XGBoost R-Squared: 0.9441004395484924

Baseline **XGBoost** is able to explain `94.41%` of vriance in daily sales, though baseline **Random Forest** was `96%`.

**Next:** Let's check feature importnace our baseline **XGBoost**:

In [83]:
pd.DataFrame({
    'Feature': all_features,
    'Importance': xgb.feature_importances_
}).sort_values('Importance', ascending=False).head(10)

                Feature  Importance
12         Assortment_b    0.272462
18            Customers    0.238685
8           StoreType_b    0.133995
10          StoreType_d    0.112155
20                Promo    0.042391
13         Assortment_c    0.026552
0           DayOfWeek_1    0.021242
24               Promo2    0.015961
22  CompetitionDistance    0.015887
25      Promo2SinceWeek    0.011690

Interesting, our baseline **XGBoost** is prioritizing `Assortment_b` over `Customers`(2nd most importnat).